// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8ae8lZ3ef5OyBaobImdvzkn4eh-a0iWc',
    appId: '1:240604459905:web:a923343af4eb6176f76e80',
    messagingSenderId: '240604459905',
    projectId: 'homeremote-a209a',
    authDomain: 'homeremote-a209a.firebaseapp.com',
    storageBucket: 'homeremote-a209a.appspot.com',
    measurementId: 'G-8VB061DVZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAGUEoL3ETyrJIwq9WJj1d0r6BJazLn0M',
    appId: '1:240604459905:android:09b82ae1a729556ff76e80',
    messagingSenderId: '240604459905',
    projectId: 'homeremote-a209a',
    storageBucket: 'homeremote-a209a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARJyNP8Eh4lunqBOE90dnMNZULEl8Xc80',
    appId: '1:240604459905:ios:503391d2923e3e4df76e80',
    messagingSenderId: '240604459905',
    projectId: 'homeremote-a209a',
    storageBucket: 'homeremote-a209a.appspot.com',
    iosClientId: '240604459905-3bt4q4e6iln1u0ith9ofjfncfha5ibqn.apps.googleusercontent.com',
    iosBundleId: 'com.example.homecontroller',
  );
}
